import { ConvexHttpClient } from "convex/browser";

const CONVEX_URL = process.env.NEXT_PUBLIC_CONVEX_URL ?? "https://earnest-spaniel-753.convex.cloud";

function getClient(): ConvexHttpClient {
  return new ConvexHttpClient(CONVEX_URL);
}

/**
 * Query a pending signup's invite token by email.
 * Uses the public validateInviteToken flow indirectly — since we can't call
 * authenticated queries from E2E setup, we query pendingSignups via a
 * one-off Convex action if available, or fall back to polling the
 * accept-invite page.
 *
 * For E2E we read the token from the test email file written by global-setup.
 */
export async function getSignupByEmailViaConvex(
  email: string,
): Promise<{ inviteToken?: string; status: string } | null> {
  // In E2E context we can't easily call authenticated Convex queries.
  // The cross-app test handles this by logging in as admin and extracting
  // the token from the admin UI.
  // This helper is a placeholder for direct DB access if we add an
  // internal query for testing.
  const client = getClient();
  void client; // suppress unused
  void email;
  return null;
}

/**
 * Read the test email generated by global-setup.
 */
export function getTestEmail(): string {
  const fs = require("fs");
  const path = require("path");
  const emailFile = path.join(__dirname, "..", ".test-email.txt");
  try {
    return fs.readFileSync(emailFile, "utf-8").trim();
  } catch {
    return `e2e-${Date.now()}@test.com`;
  }
}
